Repository TechnionYP5779/team6, pull requests merged in 2018-12, with the labels that each got.

#164 Started working on #163, local server works, need to add more needed …
  src/main/java/server/OurServer.java
Labels: 3 - Review, in progress

#165 Finished class Time including tests, closes #158
  src/main/java/parking/Time.java
  src/test/java/parking/TimeTest.java
Labels: in progress

#185 cleaned up and spartanized
  src/main/java/server/OurServer.java
Labels: in progress

#194 added a new spot form. #182
  frontend/src/app/app.module.ts
  frontend/src/app/become-host/become-host.component.html
  frontend/src/app/rent-spot-form/rent-spot-form.component.css
  frontend/src/app/rent-spot-form/rent-spot-form.component.html
  frontend/src/app/rent-spot-form/rent-spot-form.component.spec.ts
  frontend/src/app/rent-spot-form/rent-spot-form.component.ts
  frontend/src/app/rent-spot.ts
  frontend/src/assets/forms.css
  frontend/src/index.html
Labels: gui, in progress

#202 Added javadocs to class Time
  .classpath
  src/main/java/parking/Time.java
  src/test/java/parking/RentSlotTest.java
Labels: in progress

#210 update login and sign up
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/login/login.component.css
  frontend/src/app/login/login.component.html
  frontend/src/app/login/login.component.ts
  frontend/src/app/navbar/navbar.component.css
  frontend/src/app/navbar/navbar.component.html
  frontend/src/app/navbar/navbar.component.ts
  frontend/src/app/sign-up/sign-up.component.css
  frontend/src/app/sign-up/sign-up.component.html
  frontend/src/app/sign-up/sign-up.component.ts
  frontend/src/index.html
  frontend/src/styles.css
Labels: in progress

#212 started working on #203 - Jetty is my choice
  pom.xml
  src/main/java/server/JettyServer.java
  src/main/java/server/servlet/RootServlet.java
Labels: in progress

#215 Updated Jetty to the latest version to avoid any vulnerabilities
  pom.xml
Labels: in progress

#211 add httpclient as a service
  .classpath
  frontend/src/app/app.module.ts
  frontend/src/app/rent-spot-form/rent-spot-form.component.ts
  frontend/src/app/web.service.ts
Labels: in progress

#220 Added SQL Utilities class and SQL example
  src/main/java/database/DBMain.java
  src/main/java/database/QueryResults.java
  src/main/java/database/SQLUtils.java
Labels: ParkingRenting, in progress

#219 Server is working, auth0 work complete
  .classpath
  .project
  pom.xml
  src/main/java/com/auth0/example/Auth0Filter.java
  src/main/java/com/auth0/example/AuthenticationControllerProvider.java
  src/main/java/com/auth0/example/CallbackServlet.java
  src/main/java/com/auth0/example/HomeServlet.java
  src/main/java/com/auth0/example/LoginServlet.java
  src/main/java/com/auth0/example/LogoutServlet.java
  src/main/java/fluent/ly/box.java
  src/main/java/il/org/spartan/CSVLine.java
  src/main/java/il/org/spartan/tables/Row.java
  src/main/java/parking/Address.java
  src/main/java/parking/ParkingSpot.java
  src/main/java/parking/RentSlot.java
  src/main/java/parking/Time.java
  src/main/java/parking/User.java
  src/main/java/server/JettyServer.java
  src/main/java/server/RootServlet.java
  src/main/java/server/WEB-INF/protect.html
  src/main/java/server/WEB-INF/web.xml
Labels: ParkingRenting, in progress

#223 adding dist folder
  frontend/dist/parking-renting-project/3rdpartylicenses.txt
  frontend/dist/parking-renting-project/assets/forms.css
  frontend/dist/parking-renting-project/assets/img/parking-logo-black.png
  frontend/dist/parking-renting-project/assets/img/parking-logo-white.png
  frontend/dist/parking-renting-project/favicon.ico
  frontend/dist/parking-renting-project/fontawesome-webfont.674f50d287a8c48dc19b.eot
  frontend/dist/parking-renting-project/fontawesome-webfont.912ec66d7572ff821749.svg
  frontend/dist/parking-renting-project/fontawesome-webfont.af7ae505a9eed503f8b8.woff2
  frontend/dist/parking-renting-project/fontawesome-webfont.b06871f281fee6b241d6.ttf
  frontend/dist/parking-renting-project/fontawesome-webfont.fee66e712a8a08eef580.woff
  frontend/dist/parking-renting-project/index.html
  frontend/dist/parking-renting-project/main.f7691f8415a03e39ff5d.js
  frontend/dist/parking-renting-project/polyfills.20ab2d163684112c2aba.js
  frontend/dist/parking-renting-project/runtime.ec2944dd8b20ec099bf3.js
  frontend/dist/parking-renting-project/styles.49737a638edddaa88626.css
  frontend/node_modules/.cache/terser-webpack-plugin/content-v2/sha512/03/f7/1cfec44ef6530f743050de0f2e3f47433e03d3caba025319c5b09d0a6c4788bfd55fc136ddcd06bf87d07d1884a857ff486ba8cdfa4c48331f19fedc6938
  frontend/node_modules/.cache/terser-webpack-plugin/content-v2/sha512/8d/e0/e2610934d4eb780aa886862331cff55f38d3f80d461372e2e1a37e5617bf6e2a8a915880292ee7f36b634bf094164ff19c828ea97a491a1a3734b25f41e9
  frontend/node_modules/.cache/terser-webpack-plugin/content-v2/sha512/94/c5/ebfa3ed616932dd25d92eac8b92827a6a0072a4f3f5f9dea47df07900b72998402247d6c5e2f046bb67a527babb116f051fe5722db123d42efe80cb1c5cc
  frontend/node_modules/.cache/terser-webpack-plugin/content-v2/sha512/bc/5c/c1aa5afc83a325006bbab1b1ea7f9212b166332ee76503defa25b3558e53b8283f021ab0d8432bf3cc572038d538ae0364b278864b2318e4c5cb4f1bb9df
  frontend/node_modules/.cache/terser-webpack-plugin/index-v5/2a/96/b8178fb803a07f460648cb8ca28aa8ee4e7c56a92365f9464b8fae5c1370
  frontend/node_modules/.cache/terser-webpack-plugin/index-v5/3f/6b/b2cf530f36fcab1cd4cc44c2a9b4e34f96ff93968ef698fcf33531f349c7
  frontend/node_modules/.cache/terser-webpack-plugin/index-v5/67/7b/86687917982cf2790c9f46375b80f28ea2cdc641ebf1352f707e63f58763
  frontend/node_modules/.cache/terser-webpack-plugin/index-v5/f5/fd/fb367ea2dc7a4f4f0c196cb4a4ab71c48cf2fa7e993dca8f3d24b4d2df8e
Labels: in progress

#224 changed WEB-INF location
  frontend/WEB-INF/protect.html
  frontend/WEB-INF/web.xml
  src/main/java/com/auth0/example/HomeServlet.java
  src/main/java/server/JettyServer.java
Labels: in progress

#226 Post request
  src/main/java/com/auth0/example/CallbackServlet.java
  src/main/java/com/auth0/example/LetSpotServlet.java
  src/main/java/database/DBMain.java
  src/main/java/parking/OurSystem.java
  src/main/java/parking/RentSlot.java
  src/main/java/parking/Seller.java
  src/main/java/parking/User.java
  src/main/java/server/JettyServer.java
Labels: in progress

#227 Front end
  frontend/src/app/rent-spot-form/rent-spot-form.component.ts
  frontend/src/app/web.service.ts
Labels: in progress

#225 /portal/home now redirects to localhost:4200
  src/main/java/com/auth0/example/HomeServlet.java
Labels: in progress

#231 added parking db skeleton
  src/main/java/database/ParkingDataBase.java
Labels: in progress

#230 formatted and spartanized
  src/main/java/database/DBMain.java
  src/main/java/parking/OurSystem.java
Labels: ParkingRenting, in progress

#239 Geocoding address
  pom.xml
  src/main/java/database/ParkingDataBase.java
  src/main/java/mapUtils/basicUtils.java
  src/main/java/parking/Address.java
  src/main/java/parking/Buyer.java
  src/main/java/parking/OurSystem.java
  src/main/java/parking/ParkingSpot.java
  src/main/java/parking/RentSlot.java
  src/main/java/parking/Seller.java
  src/main/java/parking/User.java
  src/test/java/parking/ParkingSpotTest.java
  src/test/java/parking/RentSlotTest.java
  src/test/java/parking/UserTest.java
Labels: in progress

#241 GUI: login form - fix signup link
  frontend/src/app/login/login.component.ts
  frontend/src/app/navbar/navbar.component.ts
Labels: gui, in progress

#243 Frontend branch
  frontend/src/app/app.module.ts
  frontend/src/app/find-parking/find-parking.component.html
  frontend/src/app/find-parking/find-parking.component.ts
  frontend/src/app/rent-spot-dialog/rent-spot-dialog.component.css
  frontend/src/app/rent-spot-dialog/rent-spot-dialog.component.html
  frontend/src/app/rent-spot-dialog/rent-spot-dialog.component.spec.ts
  frontend/src/app/rent-spot-dialog/rent-spot-dialog.component.ts
Labels: in progress

#247 Idans miracle
  .classpath
  src/main/java/com/auth0/example/Auth0Filter.java
  src/main/java/com/auth0/example/HomeServlet.java
  src/main/java/com/auth0/example/LetSpotServlet.java
  src/main/java/com/auth0/example/RemoveSpotServlet.java
  src/main/java/com/auth0/example/RentSpotServlet.java
  src/main/java/com/auth0/example/SearchUserSpotsServlet.java
  src/main/java/com/auth0/example/ServerSideLoginServlet.java
  src/main/java/com/auth0/example/ServerSideLogoutServlet.java
  src/main/java/com/auth0/example/UnrentSpotServlet.java
  src/main/java/com/auth0/example/auth0.java
  src/main/java/database/DBMain.java
  src/main/java/database/ParkingDataBase.java
  src/main/java/database/QueryResults.java
  src/main/java/database/SQLUtils.java
  src/main/java/il/org/spartan/CSVLine.java
  src/main/java/il/org/spartan/tables/Row.java
  src/main/java/mapUtils/basicUtils.java
  src/main/java/parking/Address.java
  src/main/java/parking/Buyer.java
  src/main/java/parking/OurSystem.java
  src/main/java/parking/ParkingSpot.java
  src/main/java/parking/RentSlot.java
  src/main/java/parking/Seller.java
  src/main/java/parking/User.java
  src/test/java/il/org/spartan/UtilsTest.java
  src/test/java/parking/AddressTest.java
  src/test/java/parking/ParkingSpotTest.java
  src/test/java/parking/RentSlotTest.java
  src/test/java/parking/TimeTest.java
  src/test/java/parking/UserTest.java
Labels: ParkingRenting, in progress

#259 Added coordinates distance calculation and added fit function in OurS…
  src/main/java/mapUtils/basicUtils.java
  src/main/java/parking/OurSystem.java
Labels: in progress

#260 Added new methods to DB
  src/main/java/database/DBMain.java
  src/main/java/database/ParkingDataBase.java
Labels: in progress

#248 fixed form
  .classpath
  frontend/dist/parking-renting-project/assets/img/get_spot_wait_line1.png
  frontend/dist/parking-renting-project/assets/img/get_spot_wait_line2.png
  frontend/dist/parking-renting-project/main.js
  frontend/dist/parking-renting-project/main.js.map
  frontend/src/app/app.module.ts
  frontend/src/app/find-parking/find-parking.component.html
  frontend/src/app/find-parking/find-parking.component.ts
  frontend/src/app/login/login.component.html
  frontend/src/app/login/login.component.ts
  frontend/src/app/navbar/navbar.component.html
  frontend/src/app/navbar/navbar.component.ts
  frontend/src/app/rent-spot-dialog/rent-spot-dialog.component.html
  frontend/src/app/rent-spot-dialog/rent-spot-dialog.component.ts
  frontend/src/app/rent-spot-form/rent-spot-form.component.html
  frontend/src/app/rent-spot-form/rent-spot-form.component.ts
  frontend/src/app/web.service.ts
  frontend/src/assets/img/get_spot_wait_line1.png
  frontend/src/assets/img/get_spot_wait_line2.png
Labels: in progress

#264 added some functions to OurSystem and added documentation to OurSyste…
  src/main/java/parking/OurSystem.java
Labels: in progress

#266 Auth post
  frontend/dist/parking-renting-project/main.js
  frontend/dist/parking-renting-project/main.js.map
  frontend/src/app/rent-spot-form/rent-spot-form.component.ts
Labels: in progress

#268 GUI: Update "Find Parking" page
  frontend/src/app/app.module.ts
  frontend/src/app/find-parking/find-parking.component.css
  frontend/src/app/find-parking/find-parking.component.html
  frontend/src/app/find-parking/find-parking.component.ts
  frontend/src/app/rent-spot-dialog/rent-spot-dialog.component.css
  frontend/src/app/rent-spot-dialog/rent-spot-dialog.component.html
Labels: gui, in progress

#270 Master with server
  src/main/java/com/auth0/example/Auth0Filter.java
  src/main/java/com/auth0/example/LetSpotServlet.java
  src/main/java/com/auth0/example/RemoveSpotServlet.java
  src/main/java/com/auth0/example/RentSpotServlet.java
  src/main/java/com/auth0/example/SearchAllAvailableSpotsServlet.java
  src/main/java/com/auth0/example/SearchUserSpotsServlet.java
  src/main/java/com/auth0/example/ServerSideLoginServlet.java
  src/main/java/com/auth0/example/ServerSideLogoutServlet.java
  src/main/java/com/auth0/example/UnrentSpotServlet.java
  src/main/java/database/DBMain.java
  src/main/java/database/ParkingDataBase.java
  src/main/java/il/org/spartan/CSVLine.java
  src/main/java/il/org/spartan/tables/Row.java
  src/main/java/mapUtils/basicUtils.java
  src/main/java/parking/OurSystem.java
Labels: in progress

#271 Update README.md
  README.md
Labels: in progress

#277 Auth post
  frontend/dist/parking-renting-project/main.js
  frontend/dist/parking-renting-project/main.js.map
  frontend/src/app/find-parking/find-parking.component.html
  frontend/src/app/find-parking/find-parking.component.ts
  frontend/src/app/web.service.ts
Labels: in progress

#279 GUI: find parking page: zoom map when select row in table
  frontend/src/app/app.module.ts
  frontend/src/app/find-parking/find-parking.component.css
  frontend/src/app/find-parking/find-parking.component.html
  frontend/src/app/find-parking/find-parking.component.ts
Labels: gui, in progress

#283 Auth post
  frontend/dist/parking-renting-project/main.js
  frontend/dist/parking-renting-project/main.js.map
  frontend/src/app/find-parking/find-parking.component.ts
  frontend/src/app/rent-spot-form/rent-spot-form.component.ts
  frontend/src/app/web.service.ts
Labels: in progress

#284 Oursystem changed json field from parkingSpotID to id
  src/main/java/parking/OurSystem.java
Labels: in progress

#287 GUI: add "my profile" page (start working on: rent spot page - check if user is login)
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/find-parking/find-parking.component.ts
  frontend/src/app/navbar/navbar.component.html
  frontend/src/app/profile/profile.component.css
  frontend/src/app/profile/profile.component.html
  frontend/src/app/profile/profile.component.spec.ts
  frontend/src/app/profile/profile.component.ts
  frontend/src/app/rent-spot-dialog/rent-spot-dialog.component.ts
Labels: in progress

#273 Address validation
  src/main/java/mapUtils/InvalidAddressException.java
  src/main/java/mapUtils/basicUtils.java
  src/main/java/parking/OurSystem.java
Labels: in progress

#289 Added more filters
  src/main/java/mapUtils/basicUtils.java
  src/main/java/parking/OurSystem.java
Labels: in progress

#286 Added new servlet
  src/main/java/com/auth0/example/SearchParametersServlet.java
Labels: in progress

#290 GUI: update my profile page (add delete button)
  frontend/src/app/not-found/not-found.component.css
  frontend/src/app/not-found/not-found.component.html
  frontend/src/app/profile/profile.component.html
  frontend/src/app/profile/profile.component.ts
  frontend/src/app/rent-spot-form/rent-spot-form.component.html
  frontend/src/app/rent-spot-form/rent-spot-form.component.ts
Labels: in progress

#291 added userinfo servlet
  frontend/dist/parking-renting-project/main.js
  frontend/dist/parking-renting-project/main.js.map
  frontend/src/app/web.service.ts
  src/main/java/com/auth0/example/UserInfoServlet.java
  src/main/java/server/JettyServer.java
Labels: in progress

#285 Auth post
  .classpath
  frontend/dist/parking-renting-project/main.js
  frontend/dist/parking-renting-project/main.js.map
  frontend/src/app/find-parking/find-parking.component.ts
  frontend/src/app/navbar/navbar.component.html
  frontend/src/app/navbar/navbar.component.ts
  frontend/src/app/profile/profile.component.html
  frontend/src/app/profile/profile.component.ts
  frontend/src/app/web.service.ts
  src/main/java/com/auth0/example/RentSpotServlet.java
  src/main/java/com/auth0/example/SearchParametersServlet.java
  src/main/java/mapUtils/basicUtils.java
  src/main/java/parking/OurSystem.java
  src/main/java/server/JettyServer.java
Labels: in progress

#292 fixed rent
  frontend/dist/parking-renting-project/main.js
  frontend/dist/parking-renting-project/main.js.map
  frontend/src/app/profile/profile.component.ts
  frontend/src/app/web.service.ts
  src/main/java/com/auth0/example/RentSpotServlet.java
Labels: in progress

#294 trying to fix bugs
  .classpath
  frontend/dist/parking-renting-project/main.js
  frontend/dist/parking-renting-project/main.js.map
  frontend/src/app/profile/profile.component.ts
  src/main/java/com/auth0/example/RentSpotServlet.java
Labels: in progress

#295 Fixed bugs
  frontend/dist/parking-renting-project/main.js
  frontend/dist/parking-renting-project/main.js.map
  frontend/src/app/profile/profile.component.html
  frontend/src/app/profile/profile.component.ts
  frontend/src/app/web.service.ts
  src/main/java/com/auth0/example/SearchBuyerSpotsServlet.java
  src/main/java/com/auth0/example/SearchUserSpotsServlet.java
  src/main/java/database/ParkingDataBase.java
  src/main/java/parking/OurSystem.java
  src/main/java/parking/ParkingSpot.java
Labels: in progress
